### ISSUE TITLE
Rename main to hugo

### ISSUE THREAD

**Issue by RagdollClash** [yuzu-mirror/yuzu-mirror.github.io#4]
Judging from the workflow, seems that the site will only properly show up if the branch is named hugo?

```
on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]
  schedule:
    - cron: '25 0 * * *'
```

It might also be worth modifying `site/config.toml` to use the mirror url instead.
